server:
  port: "8080"
  host: "0.0.0.0"
  debug: false
  cors_origins:
    - "*"
  rate_limiting:
    enabled: true
    requests_per_minute: 60

database:
  type: "sqlite"
  database: "./data/forms.db"

email:
  provider: "smtp"
  smtp:
    host: "smtp.gmail.com"
    port: 587
    username: ""  # Set via environment variable SMTP_USERNAME
    password: ""  # Set via environment variable SMTP_PASSWORD
    from: ""      # Set via environment variable SMTP_FROM

notifications:
  ntfy:
    enabled: true
    url: "https://ntfy.sh"
    topic: "pinepods-forms"
    token: ""     # Set via environment variable NTFY_TOKEN

forms:
  storage_dir: "./submissions"
  forms:
    internal-testing-signup:
      name: "PinePods Internal Testing Sign-up"
      description: "Sign up for early access to PinePods beta versions"
      fields:
        - name: "name"
          type: "text"
          required: true
          label: "Full Name"
          placeholder: "Enter your full name"
        - name: "email"
          type: "email"
          required: true
          label: "Email Address"
          placeholder: "Enter your email address"
          validation: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
        - name: "platform"
          type: "select"
          required: true
          label: "Platform"
          placeholder: "android"
        - name: "wantsNews"
          type: "boolean"
          required: false
          label: "Wants News Updates"
          placeholder: "false"
        - name: "newsEmail"
          type: "email"
          required: false
          label: "News Email Address"
          placeholder: "Optional news email"
      actions:
        - type: "google_play_add_tester"
          config:
            track: "internal"
        - type: "send_email"
          config:
            template: "internal-testing"
        - type: "log"
          config:
            message: "New internal testing signup processed"
      validation:
        max_submissions_per_hour: 10
        require_captcha: false
      email:
        enabled: true
        template: "internal-testing"
        subject: "Welcome to PinePods Internal Testing!"
        send_confirmation: true

    contact-form:
      name: "Contact Form"
      description: "General contact form for inquiries"
      fields:
        - name: "name"
          type: "text"
          required: true
          label: "Name"
          placeholder: "Your name"
        - name: "email"
          type: "email"
          required: true
          label: "Email"
          placeholder: "your.email@example.com"
        - name: "subject"
          type: "text"
          required: true
          label: "Subject"
          placeholder: "What is this about?"
        - name: "message"
          type: "textarea"
          required: true
          label: "Message"
          placeholder: "Your message here..."
      actions:
        - type: "send_email"
          config:
            template: "confirmation"
        - type: "log"
          config:
            message: "New contact form submission"
      validation:
        max_submissions_per_hour: 5
        require_captcha: false
      email:
        enabled: true
        template: "confirmation"
        subject: "Thank you for contacting us!"
        send_confirmation: true

    feedback-form:
      name: "Feedback Form"
      description: "Submit feedback, bug reports, and feature requests"
      fields:
        - name: "feedback"
          type: "textarea"
          required: true
          label: "Your Feedback"
          placeholder: "Tell us what you think, report a bug, or suggest a feature..."
        - name: "email"
          type: "email"
          required: false
          label: "Email (optional)"
          placeholder: "your.email@example.com"
        - name: "platform"
          type: "select"
          required: false
          label: "Platform"
          placeholder: "web"
        - name: "category"
          type: "select"
          required: false
          label: "Category"
          placeholder: "general"
        - name: "page"
          type: "text"
          required: false
          label: "Page/Feature (optional)"
          placeholder: "Which page or feature is this about?"
      actions:
        - type: "send_feedback_email"
          config:
            template: "feedback-notification"
        - type: "log"
          config:
            message: "New feedback submission received"
      validation:
        max_submissions_per_hour: 10
        require_captcha: false
      email:
        enabled: true
        template: "feedback-confirmation"
        subject: "Thanks for your feedback!"
        send_confirmation: true

google_play:
  service_account_file: ""  # Set via environment variable GOOGLE_SERVICE_ACCOUNT_FILE
  package_name: ""          # Set via environment variable GOOGLE_PACKAGE_NAME

analytics:
  enabled: true
  secret_key: ""            # Set via environment variable ANALYTICS_SECRET_KEY

admin:
  username: ""              # Set via environment variable ADMIN_USERNAME
  password: ""              # Set via environment variable ADMIN_PASSWORD

feedback:
  recipient_email: ""       # Set via environment variable FEEDBACK_EMAIL